### ISSUE TITLE
Modify the resulting path into a decoded form to make links more compact.

### ISSUE THREAD

**Issue by aldrchi** [marcjulianschwarz/obsidian-file-link#10]
Implemented now the following link format:
```
 - [the-ultimate-hitchhikers-guide-to-the-galaxy.epub](file:///E%3A%5CBooks%5CFiction%5Cthe-ultimate-hitchhikers-guide-to-the-galaxy.epub)
```

The more compact format:
```
 - [the-ultimate-hitchhikers-guide-to-the-galaxy.epub](<file:///E:\Books\Fiction\the-ultimate-hitchhikers-guide-to-the-galaxy.epub>)
```
`<file:///path>`, where path without % url encoded parts

### Edit by @marcjulianschwarz:
- Add this as a setting which is turned on by default
- Users should still be able to use the encoded syntax if they prefer it -> compatibility with other markdown environments

**Comment by marcjulianschwarz** [comment]
Does this work on Windows and Mac?

**Comment by aldrchi** [comment]
At the moment on Windows works format with encoded symbols (%3A...) instead of the more compact format. About Mac I don't know.

**Comment by marcjulianschwarz** [comment]
I have tried it on Mac and it works. Do you have any resources on why this is working? Is this Obsidian / markdown specific syntax?

**Comment by aldrchi** [comment]
I don't know why it is working. I only know that before it only worked in the Obsidian View mode (the file was opened in the program intended for it), and later the developers of Obsidian apparently made changes and it works on both Editing and View modes. It is possible that this is specific of the Obsidian.

**Comment by marcjulianschwarz** [comment]
Ok thank you.

Then I will add this as an option, to make sure notes with local links will still be compatible with other markdown editors/readers.

**Comment by aldrchi** [comment]
Thank you. That's a good idea.

**Comment by marcjulianschwarz** [comment]
This is now an option in version 1.1.3. You can update the extension in the store.
