### ISSUE TITLE
Feature Request: Convert long links to short links; find broken links

### ISSUE THREAD

**Issue by raisabelatrix** [marcjulianschwarz/obsidian-file-link#11]
I recently just discovered the short links option 🙃, and I really want to change all my old long links to short links so that the note markdown looks cleaner

And not sure if this is doable within Obsidian, but it would be nice to have a pane listing all broken external links (which happens when you rename or reorganize files outside your vault). Similar to how the Dangling Links plugin works, but for external links

**Comment by marcjulianschwarz** [comment]
Hi @raisabelatrix,

thank you for the feature request.
I think I should be able to implement both features. They sound really useful.

For the second request, should this be a command (e.g. Show all broken links) which will list all links that are broken?

**Comment by raisabelatrix** [comment]
> For the second request, should this be a command (e.g. Show all broken links) which will list all links that are broken? 

By listing links, do you mean listing them in a note?

What I had in mind was that the plugin opens a pane on the sidebar listing all broken external links as well as a list of which notes have the broken link so you can easily navigate to them

**Comment by marcjulianschwarz** [comment]
I thought about listing them in the „command menu“.

However now I would say that your idea with the sidebar pane makes more sense. Though I don’t really have that much experience with the Obsidian API which means that it might take me a while to get this done.

**Comment by raisabelatrix** [comment]
> I thought about listing them in the „command menu“.

Ooh, if it's in the command palette, then that's okay too

**Comment by marcjulianschwarz** [comment]
Closed as not planned.
