### ISSUE TITLE
Unable to link folder

### ISSUE THREAD

**Issue by skirkby** [marcjulianschwarz/obsidian-file-link#12]
Hi,

Thanks for a great plugin!  I just started using it, and it comes close to filling an important need for me!

One feature that it seems was thought of, but doesn't appear to work for me, is linking to a folder and not a file.

Maybe I misunderstand how it is supposed to work ... is it possible to link to only a folder, without having to select a file?

Right now, when I execute the "Add File Link" command, I get a dialog that has a "Link Folder" check box, but if I select it, I still have to select a file (the name for which becomes the text of the link).  It doesn't seem possible to select a folder.  (I am on Windows 10.)

In addition, after selecting the file, it doesn't put the correct folder in the link.  It puts the *parent folder* of the file's folder as the link.

For example, if I select c:\Users\sean.kirkby\OneDrive - Personal\Documents\Projects\projects-index.md, the link will be inserted like this:

          [projects-index](file:///C%3A%2FUsers%2Fsean.kirkby%2FOneDrive%2FDocuments)

It misses adding the "Projects" folder in the path, and uses the selected filename as the text (rather than the folder name).

I think the idea is on-track, but doesn't seem to work. My use case is:  I typically need to put a link to a local projects folder that contains other material for the project accessed by other services, and I'd love to just have a link that opened the related folder from an index/MOC note in Obsidian.  Hosting the project folder for a project in the Obsidian vault isn't an option.

Thanks again for an awesome plugin!

**Comment by marcjulianschwarz** [comment]
Hi everyone,
it seems to me that this is a limitation of the native file selection menu. If anyone knows whether a folder selection is possible with the native file selection menu, please let me know or open a pull request with a fix.

I don't know how one could get around this limitation without having to rewrite the entire file selection menu from scratch.

**Comment by marcjulianschwarz** [comment]
closed by #13
