### ISSUE TITLE
How to update to v 1.1.0?

### ISSUE THREAD

**Issue by Hileotech** [marcjulianschwarz/obsidian-file-link#2]
Just a quick question: in Obsidian "official repository" I stil can't see v 1.1.0? Is this lag due to "Obsidian-review-system" or wanted by the dev (you)?

And: should I want to update manually would it be enough to copy-paste the new file(s) in .obsidian/plugin/etc folder or should I need more expertise?

**Comment by marcjulianschwarz** [comment]
I updated the readme and code but didn't yet publish the new release. 
Didnt know that an update to the readme file would instantly appear in the plugin itself.

You can copy and paste the files, but you would have to compile the main.ts file to main.js with npm.
I suggest waiting for the official release and then updating the plugin in Obsidian.

Will probably release it today but I can let you know when its ready.

**Comment by Hileotech** [comment]
Great to hear. Thank you for your answer!

**Comment by marcjulianschwarz** [comment]
Version 1.1.0 has been released. You can now update the plugin within Obsidian.
