### ISSUE TITLE
Link folders instead of files

### ISSUE THREAD

**Issue by balola** [marcjulianschwarz/obsidian-file-link#3]
Would it be possible to select the link type (folders or files) not just in the plugin options tab, but on the fly, when we select the files or folder. Sometimes one is better than the other.
Thanks
Füles

**Comment by marcjulianschwarz** [comment]
Just implemented this. Will need to test the code first and then I will let you know when it is released.

<img width="652" alt="Bildschirmfoto 2021-09-24 um 13 14 57" src="https://user-images.githubusercontent.com/67844154/134665762-78a383fe-afd2-4e29-a46b-34b2fedc320a.png">

**Comment by balola** [comment]
Great, what I thought. Füles

Az Android Outlook<https://aka.ms/AAb9ysg> letöltése
________________________________

**Comment by balola** [comment]
On the other hand, it is really great work, earlier I used "File path to URI" (I helped to implement network path), but with your plugin it is easier to select file(s) and insert them. Pls update when your plugin is tested.
Füles

**Comment by marcjulianschwarz** [comment]
Version 1.1.0 has been released. It includes this requested feature.

Thank you for the feedback!

**Comment by balola** [comment]
Hi,

Something goes wrong with me, nor embed nor folder link does not want to work.
Füles

**Comment by marcjulianschwarz** [comment]
Hi, 

do you use windows? I wasn’t able to test it on windows yet since I don’t have a windows device right now.
If you do have windows you might need to wait until the end of this week. I will have access to a windows device by then.

**Comment by balola** [comment]
Hi, yes I have. Füles

Marc Julian Schwarz ***@***.***> ezt írta (időpont: 2021.
szept. 28., K 8:41):

**Comment by marcjulianschwarz** [comment]
Sorry for the delay. Everything has now been tested on windows and should be working there too. The release is ready to be downloaded from the community plugins tab.

Thank you for the feature request.
