### ISSUE TITLE
Possibly to take any folder, not only on the end of the path

### ISSUE THREAD

**Issue by Paulchen312** [marcjulianschwarz/obsidian-file-link#6]
Hi there, 
nice work with your plugin.

Is it possible to take any folder for the link. My problem is that I have the following path:

C://Programs/Obsidian/Files/xyz.txt

And I want only a link for the Obsidianfolder, but it ist only possible to get the least folder where at least one file ist. 

Thanks in advance.

Paulchen312

**Comment by marcjulianschwarz** [comment]
Hi @Paulchen312,

thank you.
I know about this problem, thanks for reminding me. I will take a look at it and tell you when I got something working.

**Comment by jmichaelegana** [comment]
Hi, any updates on this? Thank you!

**Comment by marcjulianschwarz** [comment]
Further discussion will be in #12
