### ISSUE TITLE
Add the function of right clicking on the file link to open the folder where the file is located

### ISSUE THREAD

**Issue by pisceswb** [marcjulianschwarz/obsidian-file-link#8]
I inserted a file not a folder link in obsidian, but sometimes I don't want to open the file directly, but open the folder where the file is located. Can you kindly add this function?
You can provide an execution command. People who need this function can use plug-ins such as "Customizable menu settings" to add it to the right-click menu.
Thank you!

**Comment by marcjulianschwarz** [comment]
Hi @pisceswb,

so you want to be able to have both functionalities (opening the file, opening the folder) at the same time? Did I understand that right?

I will have a look at the "Customizable Menu Settings" plugin and see if it will help.

Thank you for the feature request.

**Comment by marcjulianschwarz** [comment]
Closed as I don't want this plugin to rely on other plugins.
